### ISSUE TITLE
Metal3: values.yaml keys metal3-<subchart name> are ignored

### ISSUE THREAD

**Issue by fedcicchiello** [suse-edge/charts#10]
The values for the metal3 subcharts are not properly processed by helm.

In [charts/metal3-deploy/0.1.0/values.yaml](https://github.com/suse-edge/charts/blob/079f28a17b5fe81481310821f3c6e5f1ec9d8f70/charts/metal3-deploy/0.1.0/values.yaml) subchart keys are in the form `metal3-<subchart name>` but in order to have helm properly process them the keys should be named `<subchart name>`.

Helm version: `version.BuildInfo{Version:"v3.12.0", GitCommit:"c9f554d75773799f72ceef38c51210f1842a1dea", GitTreeState:"clean", GoVersion:"go1.20.3"}`

**Comment by dbw7** [comment]
Can you let me know if this issue still exists in #15 ?
I think from what I understand is that the other fixes should fix this one, but I want to be sure before closing it

**Comment by fedcicchiello** [comment]
I confirm that this issue has been solved by the lastest PRs, I'm closing it
