### ISSUE TITLE
metal3-deploy Helm-chart issues

### ISSUE THREAD

**Issue by sivakumars28** [suse-edge/charts#12]
Please find the error caused while trying to use the master repo metal3-deploy helm charts

helm dependency update .
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "nfs-subdir-external-provisioner" chart repository
Update Complete. ⎈Happy Helming!⎈
Error: dependency "baremetal-operator" has an invalid version/constraint format: improper constraint:

 helm install heavy-metal1 . --namespace metal-cubed1 --create-namespace
Error: INSTALLATION FAILED: template: metal3-deploy/charts/ironic/templates/configmap-ipa-downloader.yaml:14:3: executing "metal3-deploy/charts/ironic/templates/configmap-ipa-downloader.yaml" at <include (print .Template.BasePath "/bin/_get-resource.sh.tpl") .>: error calling include: template: no template "metal3-deploy/charts/ironic/templates/bin/_get-resource.sh.tpl" associated with template "gotpl"

**Comment by dbw7** [comment]
Hello, thank you for creating this issue. 
I'm currently in the middle of debugging/testing fixes for this, will keep this issue open until I push the pr that fixes it

**Comment by dbw7** [comment]
Hello, this issue has been fixed in #15
