### ISSUE TITLE
metal3/ironic: make IPA kernel console= parameter configurable

### ISSUE THREAD

**Issue by tmmorin** [suse-edge/charts#88]
Depending on the type of platform, real baremetal or emulated baremetal, the useful default setting for the kernel console isn't the same: the current value `console=ttyS0` is useful on emulated baremetal (where virsh console is easy to user to access the serial console), but on real baremetal the most useful would be to have the kernel and the IPA log on `tty0` instead.

I think it would be relevant to have a chart value to control the ipa kernel console.

**Comment by hardys** [comment]
Thanks @tmmorin - I agree we should make this configurable, either we could add a console specific variable, or perhaps it may be more flexible to add a value which overrides the entire kernel params line as mentioned on https://github.com/suse-edge/charts/issues/85 ?
