### ISSUE TITLE
Metal3: Ironic subchart's templates/bin folder missing

### ISSUE THREAD

**Issue by fedcicchiello** [suse-edge/charts#9]
Helm fails when it tries to template the metal3 chart with:
`Error: template: metal3-deploy/charts/ironic/templates/configmap-ipa-downloader.yaml:14:3: executing "metal3-deploy/charts/ironic/templates/configmap-ipa-downloader.yaml" at <include (print .Template.BasePath "/bin/_get-resource.sh.tpl") .>: error calling include: template: no template "metal3-deploy/charts/ironic/templates/bin/_get-resource.sh.tpl" associated with template "gotpl"`.

This happens because the folder at `charts/metal3-deploy/0.1.0/charts/ironic/templates/bin` is missing in this repository and exists only in [rancher-sandbox/baremetal repository](https://github.com/rancher-sandbox/baremetal/tree/master/helm-charts/metal3-deploy/charts/ironic/templates/bin) so it should be copied here.

**Comment by dbw7** [comment]
Hello! As an update I'm currently debugging/testing the charts and this fix is included. Will be pushing a pr for this once the testing is complete. Thanks!

**Comment by dbw7** [comment]
Hello, this issue has been fixed in #15
